/*
# Populate comprehensive Florida election data — Part 1: Districts & Election

## Summary
Loads all Florida political districts into the database:
- 67 counties
- 28 congressional districts (post-2020 redistricting)
- 40 state senate districts
- 120 state house districts
- 20 judicial circuits
- 67 school districts
- 28 major municipalities

Also creates a 2026 General Election with ballot contests for each district
(U.S. Representative, U.S. Senator, State Senator, State Representative, County Commissioner).

## Security
No RLS changes — uses existing public read / admin write policies on districts,
elections, and ballot_contests.
*/

INSERT INTO districts (id, name, district_type, state) VALUES
(gen_random_uuid(), 'State House District 1', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 2', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 3', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 4', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 5', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 6', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 7', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 8', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 9', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 10', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 11', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 12', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 13', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 14', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 15', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 16', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 17', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 18', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 19', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 20', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 21', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 22', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 23', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 24', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 25', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 26', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 27', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 28', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 29', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 30', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 31', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 32', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 33', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 34', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 35', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 36', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 37', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 38', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 39', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 40', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 41', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 42', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 43', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 44', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 45', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 46', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 47', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 48', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 49', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 50', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 51', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 52', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 53', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 54', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 55', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 56', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 57', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 58', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 59', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 60', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 61', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 62', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 63', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 64', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 65', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 66', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 67', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 68', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 69', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 70', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 71', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 72', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 73', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 74', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 75', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 76', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 77', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 78', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 79', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 80', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 81', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 82', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 83', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 84', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 85', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 86', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 87', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 88', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 89', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 90', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 91', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 92', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 93', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 94', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 95', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 96', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 97', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 98', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 99', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 100', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 101', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 102', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 103', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 104', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 105', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 106', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 107', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 108', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 109', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 110', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 111', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 112', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 113', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 114', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 115', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 116', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 117', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 118', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 119', 'state_house', 'Florida'),
(gen_random_uuid(), 'State House District 120', 'state_house', 'Florida'),
(gen_random_uuid(), '1st Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '2nd Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '3rd Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '4th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '5th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '6th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '7th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '8th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '9th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '10th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '11th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '12th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '13th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '14th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '15th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '16th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '17th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '18th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '19th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), '20th Judicial Circuit', 'judicial', 'Florida'),
(gen_random_uuid(), 'Alachua County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Baker County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Bay County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Bradford County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Brevard County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Broward County Public Schools', 'school', 'Florida'),
(gen_random_uuid(), 'Calhoun County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Charlotte County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Citrus County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Clay County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Collier County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Columbia County School District', 'school', 'Florida'),
(gen_random_uuid(), 'DeSoto County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Dixie County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Duval County Public Schools', 'school', 'Florida'),
(gen_random_uuid(), 'Escambia County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Flagler County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Franklin County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Gadsden County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Gilchrist County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Glades County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Gulf County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Hamilton County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Hardee County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Hendry County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Hernando County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Highlands County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Hillsborough County Public Schools', 'school', 'Florida'),
(gen_random_uuid(), 'Holmes County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Indian River County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Jackson County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Jefferson County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Lafayette County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Lake County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Lee County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Leon County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Levy County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Liberty County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Madison County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Manatee County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Marion County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Martin County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Miami-Dade County Public Schools', 'school', 'Florida'),
(gen_random_uuid(), 'Monroe County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Nassau County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Okaloosa County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Okeechobee County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Orange County Public Schools', 'school', 'Florida'),
(gen_random_uuid(), 'Osceola County School District', 'school', 'Florida'),
(gen_random_uuid(), 'School District of Palm Beach County', 'school', 'Florida'),
(gen_random_uuid(), 'Pasco County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Pinellas County Schools', 'school', 'Florida'),
(gen_random_uuid(), 'Polk County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Putnam County School District', 'school', 'Florida'),
(gen_random_uuid(), 'St. Johns County School District', 'school', 'Florida'),
(gen_random_uuid(), 'St. Lucie County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Santa Rosa County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Sarasota County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Seminole County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Sumter County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Suwannee County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Taylor County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Union County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Volusia County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Wakulla County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Walton County School District', 'school', 'Florida'),
(gen_random_uuid(), 'Washington County School District', 'school', 'Florida'),
(gen_random_uuid(), 'City of Jacksonville', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Miami', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Tampa', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Orlando', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of St. Petersburg', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Hialeah', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Tallahassee', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Fort Lauderdale', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Port St. Lucie', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Cape Coral', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Pembroke Pines', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Hollywood', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Gainesville', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Miramar', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Coral Springs', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Clearwater', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Palm Bay', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of West Palm Beach', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Lakeland', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Pompano Beach', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Davie', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Miami Gardens', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Sunrise', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Plantation', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Boca Raton', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Pensacola', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Sarasota', 'municipal', 'Florida'),
(gen_random_uuid(), 'City of Naples', 'municipal', 'Florida')
ON CONFLICT DO NOTHING;

INSERT INTO elections (id, name, election_date, description)
VALUES (gen_random_uuid(), '2026 General Election', '2026-11-03', 'Florida 2026 General Election');

INSERT INTO ballot_contests (id, election_id, district_id, office_name, contest_level, seat_description, term_length)
SELECT gen_random_uuid(), e.id, d.id, 'U.S. Representative', 'federal', NULL, '2 years'
FROM elections e, districts d
WHERE e.name = '2026 General Election' AND d.district_type = 'congressional' AND d.state = 'Florida';

INSERT INTO ballot_contests (id, election_id, district_id, office_name, contest_level, seat_description, term_length)
SELECT gen_random_uuid(), e.id, NULL, 'U.S. Senator', 'federal', 'Class 1', '6 years'
FROM elections e WHERE e.name = '2026 General Election';

INSERT INTO ballot_contests (id, election_id, district_id, office_name, contest_level, seat_description, term_length)
SELECT gen_random_uuid(), e.id, d.id, 'State Senator', 'state', NULL, '4 years'
FROM elections e, districts d
WHERE e.name = '2026 General Election' AND d.district_type = 'state_senate' AND d.state = 'Florida';

INSERT INTO ballot_contests (id, election_id, district_id, office_name, contest_level, seat_description, term_length)
SELECT gen_random_uuid(), e.id, d.id, 'State Representative', 'state', NULL, '2 years'
FROM elections e, districts d
WHERE e.name = '2026 General Election' AND d.district_type = 'state_house' AND d.state = 'Florida';

INSERT INTO ballot_contests (id, election_id, district_id, office_name, contest_level, seat_description, term_length)
SELECT gen_random_uuid(), e.id, d.id, 'County Commissioner', 'local', NULL, '4 years'
FROM elections e, districts d
WHERE e.name = '2026 General Election' AND d.district_type = 'county' AND d.state = 'Florida';
